apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: zoneprinter
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cloud.google.com/neg: '{"ingress": true}'
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: 35.244.217.159.xip.io
    http:
      paths:
      - backend:
          serviceName: zonesvc
          servicePort: 8080
        path: /zoneprinter
