apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: negdemoapp # Label for the Deployment
  name: negdemoapp # Name of Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      run: negdemoapp
  template: # Pod template
    metadata:
      labels:
        run: negdemoapp # Labels Pods from this Deployment
    spec: # Pod specification; each Pod created by this Deployment has this specification
      containers:
      - image: k8s.gcr.io/serve_hostname:v1.4 # Application to run in Deployment's Pods
        name: hostname
  
